### ISSUE TITLE
Example breaks with GITHUB_SHA var in staging.yaml 

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/github-actions-example#2]
When trying to run the `gimlet manifest template` command in an github action like in that example, it does explode due to invalid map key. Is there any additional step needed that I`m missing?

**staging.yaml**
```yaml
tag: {{ .GITHUB_SHA }}
```

`cannot unmarshal manifest: yaml: invalid map key: map[string]interface {}{".GITHUB_SHA":interface {}(nil)}`

**Comment by laszlocph** [comment]
Can you put it in quotes?

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/gimlet-website/commit/366e8f982e5f7c9530233bdab70c1491e3f96157
